name: mobile
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.4.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.3.0
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  analyzer: ^5.2.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
